import type { PlanningProfile } from './types';

export const DEFAULT_PLANNING_PROFILES: PlanningProfile[] = [
  {
    id: 'beef-thick-steak',
    label: 'Thick beef steak',
    animal: 'beef',
    role: 'main',
    preferredZones: ['indirect_medium', 'direct_high'],
    fallbackZones: ['direct_medium'],
    requiredZones: ['direct_high'],
    zoneDemand: 1,
    timingSensitivity: 'high',
    holdQuality: 'limited',
    canHoldWarm: false,
    maxHoldMinutes: 8,
    preferredServeWindowMinutes: 8,
    minRestMinutes: 6,
    defaultRestMinutes: 8,
    maxRestMinutes: 12,
    defaultCookMinutes: 26,
    minCookMinutes: 14,
    maxCookMinutes: 45,
    setupMinutes: 5,
    flipCadenceMinutes: 4,
    canBeSplitIntoPhases: true,
    conflictWeight: 9,
    warnings: ['Serve close to target time. Long holding hurts quality.'],
  },
  {
    id: 'beef-fat-cap-picanha',
    label: 'Fat-cap beef roast / picanha',
    animal: 'beef',
    role: 'main',
    preferredZones: ['indirect_medium', 'direct_medium'],
    fallbackZones: ['direct_high'],
    requiredZones: ['indirect_medium'],
    zoneDemand: 1,
    timingSensitivity: 'medium',
    holdQuality: 'good',
    canHoldWarm: true,
    maxHoldMinutes: 20,
    preferredServeWindowMinutes: 12,
    minRestMinutes: 10,
    defaultRestMinutes: 15,
    maxRestMinutes: 25,
    defaultCookMinutes: 42,
    minCookMinutes: 28,
    maxCookMinutes: 70,
    setupMinutes: 6,
    flipCadenceMinutes: 8,
    canBeSplitIntoPhases: true,
    conflictWeight: 8,
    warnings: ['Avoid long fat-cap direct exposure. Render gently before final color.'],
  },
  {
    id: 'low-slow-large',
    label: 'Large low and slow cut',
    animal: 'beef',
    role: 'main',
    preferredZones: ['smoke_low', 'indirect_low'],
    fallbackZones: ['indirect_medium'],
    requiredZones: ['smoke_low'],
    zoneDemand: 2,
    timingSensitivity: 'low',
    holdQuality: 'excellent',
    canHoldWarm: true,
    maxHoldMinutes: 90,
    preferredServeWindowMinutes: 45,
    minRestMinutes: 30,
    defaultRestMinutes: 45,
    maxRestMinutes: 120,
    defaultCookMinutes: 240,
    minCookMinutes: 150,
    maxCookMinutes: 420,
    setupMinutes: 15,
    safetyCritical: true,
    canBeSplitIntoPhases: false,
    conflictWeight: 7,
    warnings: ['Build generous buffer. This cut should drive the schedule.'],
  },
  {
    id: 'pork-low-slow-ribs-belly',
    label: 'Pork ribs / belly long cook',
    animal: 'pork',
    role: 'main',
    preferredZones: ['indirect_medium', 'indirect_low', 'smoke_low'],
    fallbackZones: ['direct_medium'],
    requiredZones: ['indirect_medium'],
    zoneDemand: 2,
    timingSensitivity: 'medium',
    holdQuality: 'good',
    canHoldWarm: true,
    maxHoldMinutes: 45,
    preferredServeWindowMinutes: 20,
    minRestMinutes: 8,
    defaultRestMinutes: 12,
    maxRestMinutes: 30,
    defaultCookMinutes: 180,
    minCookMinutes: 90,
    maxCookMinutes: 360,
    setupMinutes: 10,
    safetyCritical: true,
    canBeSplitIntoPhases: true,
    conflictWeight: 8,
    warnings: ['Cook low and steady. Keep a finish buffer and confirm safe internal temperature.'],
  },
  {
    id: 'pork-thin-iberian',
    label: 'Thin Iberian pork cut',
    animal: 'pork',
    role: 'secondary',
    preferredZones: ['direct_high', 'direct_medium'],
    fallbackZones: ['plancha'],
    zoneDemand: 1,
    timingSensitivity: 'critical',
    holdQuality: 'poor',
    canHoldWarm: false,
    maxHoldMinutes: 5,
    preferredServeWindowMinutes: 5,
    minRestMinutes: 3,
    defaultRestMinutes: 4,
    maxRestMinutes: 8,
    defaultCookMinutes: 8,
    minCookMinutes: 4,
    maxCookMinutes: 14,
    setupMinutes: 3,
    flipCadenceMinutes: 2,
    canBeSplitIntoPhases: false,
    conflictWeight: 10,
    warnings: ['Cook last. Thin Iberian cuts overcook quickly.'],
  },
  {
    id: 'chicken-safe-direct-indirect',
    label: 'Chicken safe cook',
    animal: 'chicken',
    role: 'secondary',
    preferredZones: ['indirect_medium', 'direct_medium'],
    fallbackZones: ['direct_high'],
    requiredZones: ['indirect_medium'],
    zoneDemand: 1,
    timingSensitivity: 'medium',
    holdQuality: 'good',
    canHoldWarm: true,
    maxHoldMinutes: 25,
    preferredServeWindowMinutes: 15,
    minRestMinutes: 5,
    defaultRestMinutes: 8,
    maxRestMinutes: 15,
    defaultCookMinutes: 34,
    minCookMinutes: 18,
    maxCookMinutes: 60,
    setupMinutes: 6,
    flipCadenceMinutes: 6,
    safetyCritical: true,
    canBeSplitIntoPhases: true,
    conflictWeight: 8,
    warnings: ['Use safe doneness logic. Do not offer rare chicken.'],
  },
  {
    id: 'chicken-whole-roast',
    label: 'Whole/spatchcock chicken roast',
    animal: 'chicken',
    role: 'main',
    preferredZones: ['indirect_medium', 'indirect_low', 'direct_medium'],
    fallbackZones: ['direct_high'],
    requiredZones: ['indirect_medium'],
    zoneDemand: 1,
    timingSensitivity: 'medium',
    holdQuality: 'good',
    canHoldWarm: true,
    maxHoldMinutes: 30,
    preferredServeWindowMinutes: 15,
    minRestMinutes: 8,
    defaultRestMinutes: 10,
    maxRestMinutes: 20,
    defaultCookMinutes: 65,
    minCookMinutes: 40,
    maxCookMinutes: 120,
    setupMinutes: 8,
    flipCadenceMinutes: 8,
    safetyCritical: true,
    canBeSplitIntoPhases: true,
    conflictWeight: 8,
    warnings: ['Use probe checks before serving. Whole birds need extra carryover and carve time.'],
  },
  {
    id: 'fish-fillet-fast',
    label: 'Fast fish fillet',
    animal: 'fish',
    role: 'finish',
    preferredZones: ['direct_medium', 'plancha'],
    fallbackZones: ['indirect_medium'],
    zoneDemand: 1,
    timingSensitivity: 'critical',
    holdQuality: 'poor',
    canHoldWarm: false,
    maxHoldMinutes: 3,
    preferredServeWindowMinutes: 4,
    minRestMinutes: 1,
    defaultRestMinutes: 2,
    maxRestMinutes: 4,
    defaultCookMinutes: 7,
    minCookMinutes: 4,
    maxCookMinutes: 12,
    setupMinutes: 3,
    flipCadenceMinutes: 3,
    safetyCritical: true,
    canBeSplitIntoPhases: false,
    conflictWeight: 10,
    warnings: ['Cook at the end and serve immediately.'],
  },
  {
    id: 'vegetable-side-flexible',
    label: 'Flexible vegetable side',
    animal: 'vegetable',
    role: 'side',
    preferredZones: ['direct_medium', 'plancha', 'indirect_medium'],
    fallbackZones: ['direct_high'],
    zoneDemand: 1,
    timingSensitivity: 'low',
    holdQuality: 'good',
    canHoldWarm: true,
    maxHoldMinutes: 25,
    preferredServeWindowMinutes: 20,
    minRestMinutes: 0,
    defaultRestMinutes: 0,
    maxRestMinutes: 5,
    defaultCookMinutes: 14,
    minCookMinutes: 6,
    maxCookMinutes: 30,
    setupMinutes: 3,
    flipCadenceMinutes: 5,
    canBeSplitIntoPhases: false,
    conflictWeight: 4,
  },
  {
    id: 'sausage-starter-flexible',
    label: 'Sausage / starter',
    animal: 'pork',
    role: 'starter',
    preferredZones: ['direct_medium', 'indirect_medium'],
    fallbackZones: ['direct_high'],
    zoneDemand: 1,
    timingSensitivity: 'low',
    holdQuality: 'good',
    canHoldWarm: true,
    maxHoldMinutes: 30,
    preferredServeWindowMinutes: 25,
    minRestMinutes: 2,
    defaultRestMinutes: 3,
    maxRestMinutes: 8,
    defaultCookMinutes: 16,
    minCookMinutes: 10,
    maxCookMinutes: 28,
    setupMinutes: 3,
    flipCadenceMinutes: 5,
    safetyCritical: true,
    canBeSplitIntoPhases: false,
    conflictWeight: 5,
  },
];

export const CUT_PROFILE_OVERRIDES: Record<string, string> = {
  ribeye: 'beef-thick-steak',
  striploin: 'beef-thick-steak',
  tenderloin: 'beef-thick-steak',
  tomahawk: 'beef-thick-steak',
  t_bone: 'beef-thick-steak',
  tri_tip: 'beef-fat-cap-picanha',
  picanha: 'beef-fat-cap-picanha',
  brisket: 'low-slow-large',
  chuck_roast: 'low-slow-large',
  short_ribs: 'low-slow-large',
  baby_back_ribs: 'pork-low-slow-ribs-belly',
  spare_ribs: 'pork-low-slow-ribs-belly',
  pork_belly: 'pork-low-slow-ribs-belly',
  pork_belly_slices: 'pork-thin-iberian',
  iberian_secreto: 'pork-thin-iberian',
  iberian_presa: 'pork-thin-iberian',
  chicken_breast: 'chicken-safe-direct-indirect',
  chicken_wing: 'chicken-safe-direct-indirect',
  chicken_drumstick: 'chicken-safe-direct-indirect',
  whole_chicken: 'chicken-whole-roast',
  spatchcock_chicken: 'chicken-whole-roast',
  salmon_fillet: 'fish-fillet-fast',
  virrey: 'fish-fillet-fast',
  asparagus: 'vegetable-side-flexible',
  corn_on_cob: 'vegetable-side-flexible',
  bell_peppers: 'vegetable-side-flexible',
  mushrooms: 'vegetable-side-flexible',
  chorizo: 'sausage-starter-flexible',
};
